cache:
  directories:
  - $HOME/.cache/pip
  - $HOME/.m2
  - $HOME/.mx
dist: trusty
sudo: required
group: deprecated-2017Q3
language: java
python:
  - "2.7"
addons:
  apt:
    sources:
    - deadsnakes
    packages:
    - python2.7
    - python-pip
    - gcc-4.6
    - g++-4.6
    - gfortran-4.6
    - libgmp3-dev
    - gobjc++-4.6
    - gcc-4.6-plugin-dev
    - libc++1
    - libc++abi1
    - libc++-dev
    - libc++abi-dev
    - llvm-3.8
    - clang-3.8
    - clang-format-3.8
install:
  - export MX_BINARY_SUITES="jvmci"
  - gem install mdl
  - pip install astroid==1.1.0 --user
  - pip install pylint==1.1.0 --user
  - git clone https://github.com/graalvm/mx
  - wget -O mx/ecj.jar 'https://lafo.ssw.uni-linz.ac.at/pub/sulong-deps/ecj-4.5.2.jar'
  - export JDT=`pwd`/mx/ecj.jar
  - wget https://lafo.ssw.uni-linz.ac.at/pub/sulong-deps/eclipse-jdk8-linux-x86_64.tar.gz
  - tar -xvzf eclipse-jdk8-linux-x86_64.tar.gz
  - export ECLIPSE_EXE=eclipse/eclipse
  - export DEFAULT_VM=server
  - export PATH=`pwd`/mx:$PATH
  - wget https://github.com/dougxc/openjdk8-jvmci-builder/releases/download/jvmci-0.34/openjdk1.8.0_141-jvmci-0.34-linux-amd64.tar.gz
  - tar -xzf openjdk1.8.0_141-jvmci-0.34-linux-amd64.tar.gz
  - export JAVA_HOME=`pwd`/openjdk1.8.0_141-jvmci-0.34
  - mx pulldragonegg
  - export DRAGONEGG_LLVM=`pwd`/cache/tools/llvm
  - export DRAGONEGG=`pwd`/cache/tools/dragonegg/dragonegg-3.2.src
  - mkdir llvmDir
  - cd llvmDir
  - ln -s /usr/bin/clang-3.8 clang
  - ln -s /usr/bin/clang++-3.8 clang++
  - ln -s /usr/bin/opt-3.8 opt
  - ln -s /usr/bin/llvm-link-3.8 llvm-link
  - ln -s $DRAGONEGG_LLVM/bin/clang clang-3.2
  - ln -s $DRAGONEGG_LLVM/bin/clang++ clang++-3.2
  - ln -s $DRAGONEGG_LLVM/bin/llvm-as llvm-as-3.2
  - ln -s $DRAGONEGG_LLVM/bin/opt opt-3.2
  - ln -s $DRAGONEGG_LLVM/bin/llvm-config llvm-config-3.2
  - export PATH=`pwd`:$PATH
  - cd ..
  - export CPPFLAGS=-g
script:
  - $COMPILE_COMMAND && $TEST_COMMAND
matrix:
  fast_finish: true
  include:
  - env: TEST_COMMAND='mx check --verbose' COMPILE_COMMAND=''
    jdk: oraclejdk8
  - env: TEST_COMMAND='mx unittest SulongSuite LLVMInteropTest' COMPILE_COMMAND='mx build'
    jdk: oraclejdk8
  - env: TEST_COMMAND='mx test llvm args assembly type vaargs pipe callback shootout nwcc parserTorture' COMPILE_COMMAND='mx build --dependencies SULONG_TEST'
    jdk: oraclejdk8
  - env: TEST_COMMAND='mx test gcc32' COMPILE_COMMAND='mx build --dependencies SULONG_TEST'
    jdk: oraclejdk8
  - env: TEST_COMMAND='mx test gcc38' COMPILE_COMMAND='mx build --dependencies SULONG_TEST'
    jdk: oraclejdk8
after_failure:
  - find . -iname "*.log" -print0 | xargs -0 cat
