language: java
python:
  - "2.7"
jdk:
  - oraclejdk8
addons:
  apt:
    sources:
    - deadsnakes
    packages:
    - python2.7
    - gcc-4.6
    - g++-4.6
    - gfortran-4.6
    - libgmp3-dev
    - llvm-3.3
    - gobjc++-4.6
    - gcc-4.6-plugin-dev
install:
  - gem install mdl
  - sudo pip install astroid==1.1.0
  - sudo pip install pylint==1.1.0
  - git clone https://github.com/graalvm/mx
  - wget http://ftp.halifax.rwth-aachen.de/eclipse//eclipse/downloads/drops4/R-4.5.1-201509040015/ecj-4.5.1.jar
  - mv ecj-4.5.1.jar mx/ecj.jar
  - export JDT=`pwd`/mx/ecj.jar
  - wget https://lafo.ssw.uni-linz.ac.at/slavefiles/gate/eclipse-jdk8-linux-x86_64.tar.gz
  - tar -xvzf eclipse-jdk8-linux-x86_64.tar.gz
  - export ECLIPSE_EXE=eclipse/eclipse
  - export DEFAULT_VM=server
script:
  - $TEST_COMMAND
branches:
  only:
    - master
env:
  - TEST_COMMAND='mdl .'
  - TEST_COMMAND='mx/mx su-gitlogcheck'
  - TEST_COMMAND='mx/mx pylint'
  - TEST_COMMAND='mx/mx checkstyle'
  - TEST_COMMAND='mx/mx checkoverlap'
  - TEST_COMMAND='mx/mx canonicalizeprojects'
  - TEST_COMMAND='mx/mx su-travis1'
  - TEST_COMMAND='mx/mx su-travis2'
after_failure:
  - find . -iname "*.log" -print0 | xargs -0 cat
