language: java
python:
  - "2.7"
addons:
  apt:
    packages:
      - python-pip
      - python-virtualenv
      - wget
      - mercurial

# Use Trusty to get enough RAM
sudo: required
dist: trusty

jdk:
    - openjdk11

env:
  global:
    - JVMCI_VERSION="jvmci-19.2-b01"
    - JDK8_UPDATE_VERSION="212"
    - JDK8_UPDATE_VERSION_SUFFIX=""

matrix:
  include:
  - env: JDK="jdk8" GATE="style,fullbuild" PRIMARY="substratevm"
  - env: JDK="jdk8" GATE="build,test" PRIMARY="compiler"
  - env: JDK="jdk8" GATE="build,test,helloworld" PRIMARY="substratevm"
  - env: JDK="jdk8" GATE="build,bootstraplite" PRIMARY="compiler"
  - env: JDK="jdk8" GATE="style,fullbuild,sulongBasic" PRIMARY="sulong" LLVM_VERSION="3.8" NO_FEMBED_BITCODE="true"
    addons:
      apt:
        packages:
          - python-pip
          - clang-3.8
          - llvm-3.8
          - clang-format-3.8
          - libc++1
          - libc++-dev
  - env: JDK="jdk8" GATE="build,sulong" PRIMARY="vm" DYNAMIC_IMPORTS="/sulong,/substratevm" LLVM_VERSION="6.0" DISABLE_POLYGLOT=true DISABLE_LIBPOLYGLOT=true
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
          - llvm-toolchain-trusty-6.0
        packages:
          - clang-6.0
          - llvm-6.0
          - libc++1
          - libc++-dev
  - env: JDK="jdk11" GATE="style,fullbuild" PRIMARY="compiler"
  - env: JDK="jdk11" GATE="build,test" PRIMARY="compiler"
  - env: JDK="jdk11" GATE="build,bootstraplite" PRIMARY="compiler"
# GR-16977
#  - env: JDK="jdk11" GATE="build,test,helloworld" PRIMARY="substratevm"

install:
  - |
      export MX_PATH=${TRAVIS_BUILD_DIR}/../mx
      git clone https://github.com/graalvm/mx.git ${MX_PATH}
      export PATH=${PATH}:${MX_PATH}
  - |
      if [[ ${GATE} == *style* ]]
      then
        virtualenv venv
        source venv/bin/activate
        pip install astroid==1.1.0
        pip install pylint==1.1.0

        export ECLIPSE_TAR=${TRAVIS_BUILD_DIR}/../eclipse.tar.gz
        wget https://archive.eclipse.org/eclipse/downloads/drops4/R-4.5.2-201602121500/eclipse-SDK-4.5.2-linux-gtk-x86_64.tar.gz -O ${ECLIPSE_TAR}
        tar -C ${TRAVIS_BUILD_DIR}/.. -xzf ${ECLIPSE_TAR}
        export ECLIPSE_EXE=${TRAVIS_BUILD_DIR}/../eclipse/eclipse

        # the style gate needs the full commit history for checking copyright years
        git fetch --unshallow
      fi
  - |
      if [[ ${GATE} == *fullbuild* ]]
      then
        # Only test JDT on JDK8
        if [ "${JDK}" == "jdk8" ]
        then
          export JDT=${MX_PATH}/ecj.jar
          wget https://archive.eclipse.org/eclipse/downloads/drops4/R-4.5.2-201602121500/ecj-4.5.2.jar -O ${JDT}
        fi
      fi
  - |
      if [ "${JDK}" == "jdk8" ]
      then
        JDK_TAR=${TRAVIS_BUILD_DIR}/../jdk.tar.gz
        wget https://github.com/graalvm/openjdk8-jvmci-builder/releases/download/${JVMCI_VERSION}/openjdk-8u${JDK8_UPDATE_VERSION}${JDK8_UPDATE_VERSION_SUFFIX}-${JVMCI_VERSION}-linux-amd64.tar.gz -O ${JDK_TAR}
        tar -C ${TRAVIS_BUILD_DIR}/.. -xzf ${JDK_TAR}
        export JAVA_HOME=${TRAVIS_BUILD_DIR}/../openjdk1.8.0_${JDK8_UPDATE_VERSION}-${JVMCI_VERSION}
      fi
  - |
      if [ "${LLVM_VERSION}" != "" ]
      then
        export CLANG=clang-$LLVM_VERSION
        export CLANGXX=clang++-$LLVM_VERSION
        export OPT=opt-$LLVM_VERSION
        export LLVM_AS=llvm-as-$LLVM_VERSION
        export LLVM_LINK=llvm-link-$LLVM_VERSION
      fi

script:
  - echo ${JAVA_HOME}
  - ${JAVA_HOME}/bin/java -version
  - mx --primary-suite-path ${TRAVIS_BUILD_DIR}/${PRIMARY} --java-home=${JAVA_HOME} gate --strict-mode --tags ${GATE}
after_failure:
  - cat hs_err*
