cache:
  directories:
  - projects/com.oracle.truffle.llvm.tools/tools
sudo: required
language: java
python:
  - "2.7"
jdk:
  - oraclejdk8
addons:
  apt:
    sources:
    - deadsnakes
    packages:
    - python2.7
    - gcc-4.6
    - g++-4.6
    - gfortran-4.6
    - libgmp3-dev
    - llvm-3.3
    - clang-format-3.4
    - gobjc++-4.6
    - gcc-4.6-plugin-dev
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libxml2-dev
  - sudo apt-get install -y libssl-dev
install:
  - export MX_BINARY_SUITES="jvmci"
  - gem install mdl
  - pip install astroid==1.1.0 --user `whoami`
  - pip install pylint==1.1.0 --user `whoami`
  - git clone https://github.com/graalvm/mx
  - wget -O mx/ecj.jar 'http://lafo.ssw.uni-linz.ac.at/sulong-deps/ecj-4.5.2.jar'
  - export JDT=`pwd`/mx/ecj.jar
  - wget http://lafo.ssw.uni-linz.ac.at/sulong-deps/eclipse-jdk8-linux-x86_64.tar.gz
  - tar -xvzf eclipse-jdk8-linux-x86_64.tar.gz
  - export ECLIPSE_EXE=eclipse/eclipse
  - export DEFAULT_VM=server
  - export PATH=`pwd`/mx:$PATH
  - wget https://github.com/dougxc/openjdk8-jvmci-builder/releases/download/jvmci-0.17/jdk1.8.0_91-jvmci-0.17-linux-amd64.tar.gz
  - tar -xzf jdk1.8.0_91-jvmci-0.17-linux-amd64.tar.gz
  - export JAVA_HOME=`pwd`/jdk1.8.0_91-jvmci-0.17
script:
  - $TEST_COMMAND
branches:
  only:
    - master
env:
  - TEST_COMMAND='mx su-clangformatcheck'
  - TEST_COMMAND='mx eclipseformat --primary'
  - TEST_COMMAND='mx su-mdlcheck'
  - TEST_COMMAND='mx su-gitlogcheck'
  - TEST_COMMAND='mx pylint'
  - TEST_COMMAND='mx checkstyle'
  - TEST_COMMAND='mx checkoverlap'
  - TEST_COMMAND='mx canonicalizeprojects'
  - TEST_COMMAND='mx su-travis1'
  - TEST_COMMAND='mx su-travis2'
  - TEST_COMMAND='mx su-travis3'
  - TEST_COMMAND='mx su-travis-jruby' LIBXML_LIB_HOME=/usr/lib/x86_64-linux-gnu OPENSSL_LIB_HOME=/usr/lib/x86_64-linux-gnu

after_failure:
  - find . -iname "*.log" -print0 | xargs -0 cat
