[[rule]]
files = "FutureDefaultsOptions.java"
all = [
    "vojin.jovanovic@oracle.com",
    "christian.wirth@oracle.com"
]
any = [
]
[[rule]]
files = "ClassLoaderSupport.java"
all = [
    "paul.woegerer@oracle.com",
    "vojin.jovanovic@oracle.com",
    "christian.wirth@oracle.com"
]
any = [
]