[[rule]]
files = "*"
any = [
    "doug.simon@oracle.com",
    "tom.rodriguez@oracle.com",
    "david.leopoldseder@oracle.com",
    "gergo.barany@oracle.com",
    "yudi.zheng@oracle.com",
    "raphael.m.mosaner@oracle.com",
    "quan.anh.mai@oracle.com",
]
