os:
    - linux
    - osx

language: java

env:
    - GRAALVM_VERSION="20.0.0" GRAALVM_JAVA_VERSION="8"
    - GRAALVM_VERSION="20.0.0" GRAALVM_JAVA_VERSION="11"

install:
    - cd .. && mv simpletool "simple tool" && cd "simple tool"
    - |
        if [[ "$TRAVIS_OS_NAME" == "osx" ]];   then DOWNLOAD_OS_NAME="darwin"; fi
        if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then DOWNLOAD_OS_NAME="linux"; fi
        curl -LJ "https://github.com/graalvm/graalvm-ce-builds/releases/download/vm-$GRAALVM_VERSION/graalvm-ce-java$GRAALVM_JAVA_VERSION-$DOWNLOAD_OS_NAME-amd64-$GRAALVM_VERSION.tar.gz" --output graalvm.tar.gz
        tar -xzf graalvm.tar.gz
        export JAVA_HOME="$(pwd)/graalvm-ce-java$GRAALVM_JAVA_VERSION-$GRAALVM_VERSION"
        if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export JAVA_HOME="$JAVA_HOME/Contents/Home"; fi

script:
    - mvn package
    - ./simpletool js example.js
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then shellcheck simpletool; fi
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then shellcheck runJsWithCoverage.sh; fi
