[[rule]]
files = "*"
all = [
    "christian.haeubl@oracle.com",
    "peter.hofer@oracle.com",
]
any = [
]
[[rule]]
files = "RuntimeClassLoading.java RuntimeDynamicHubMetadata.java RuntimeReflectionMetadata.java"
all = [
    "gilles.m.duboscq@oracle.com",
]
